### ISSUE TITLE
Maintainer

### ISSUE THREAD

**Issue by knownasilya** [knownasilya/interval#6]
I'd love to maintain this package, if you're up for it.

**Comment by fixedset** [comment]
Sounds good. I've added you as owner of this package in npm, and I'll transfer the repo now. Thank you!

**Comment by fixedset** [comment]
I'd like to transfer the repo to your github account (so the stars and issues follow it) but I cannot do that because you have a repo with the same name. If you rename/delete that repo I'll transfer.

**Comment by knownasilya** [comment]
That is the fork of this project. Can you merge the PR's I submitted, and then I'll delete the fork.

**Comment by knownasilya** [comment]
Deleted the fork.

**Comment by fixedset** [comment]
Good to go, I think you just have to approve the transfer. Thanks again.

**Comment by gajus** [comment]
@knownasilya Can I take it over from you? Seems to be no longer actively maintained/ used.

I would like to re-release this as a function equivalent to Postgres INTERVAL, i.e. `interval('1 hour') === 60 * 60 * 1000`.

It would prevent people writing code using magical numbers such as this:

```js
setTimeout(() => {
  throw new TimeoutError();
}, 5 * 60 * 1000);

```

and turn it into:

```js
setTimeout(() => {
  throw new TimeoutError();
}, interval('5 minute'));

```

**Comment by knownasilya** [comment]
Still maintained, feel free to submit pull requests 👍
